###########################################################
### Welcome to Beautiful Jekyll!
### This config file is meant for settings that affect your entire website. When you first
### set up your website you should go through all these settings and edit them, but after
### the initial set up you won't need to come back to this file often.
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: 国家防伪工程技术研究中心

# Your name to show in the footer
author: Some Person

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  首页: "/index"
  中心概况:
    - 中心介绍: "/intro/introduction"
    - 中心目标与定位: "/intro/index"
    - 组织架构: "/intro/org"
    - 历史沿革: "/intro/hist"
    - 行业影响: "/intro/impact"
    - 联系我们: "/intro/cont"
  研究队伍: 
    - 队伍概况: "/team/index"
    - 杰出人才: "/team/talent"
    - 特聘教授: "/team/distinguishedProfessors"
    - 研究机构: "/team/labs"
    - 测试机构: "/team/test"
  科学研究:
    - 科研项目: "/researchs/programs_index"
    - 研究方向: "/researchs/researchs_index"
  研究成果:
    - 获得奖项: "/contributions/prize"
    - 标准: "/contributions/standard"
    - 专利: "/contributions/patent"
    - 论文: "/contributions/paper"
  代表性工程化成果:
    - 全息防伪技术与制备工艺: "/industry/0"
    # - 防伪功能材料与结构-激光全息高分子材料: "/industry/3-1"
    # - 防伪功能材料与结构-全息打印机: "/industry/3-2"
    # - 防伪功能材料与结构-自组装光学防伪材料: "/industry/3-3"
    - 防伪用全息塑料及其加工技术: "/industry/7"
    - 防伪票据智能鉴伪与识读技术及装备: "/industry/2"
    - 证照防伪检测与智能鉴伪: "/industry/1"
    - 产品溯源关键技术与平台: "/industry/6"
    - 信息加密与智能IC卡: "/industry/5"
    - 生物特征识别与应用: "/industry/4"
  服务与合作:
    - 校企共建联合实验室: "/cooperations/jointLabs"
    - 服务合作机构: "/cooperations/services_index"
    - 国际合作: "/cooperations/platform"
  产业化基地:
    - 武汉华工图像技术开发有限公司: "https://www.hgimage.com/"
    - 武汉华工赛百数据系统有限公司: "https://www.hgcyberdata.com/"
    - 武汉天喻信息产业股份有限公司: "http://www.whty.com.cn/"
  新闻: "/news/index"

################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/title_new.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: false

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
title-img: /assets/img/logo.png


# If you want your website to generate an RSS feed, provide a description
# The URL for the feed will be https://<your_website>/feed.xml
rss-description: This website is a virtual proof that I'm awesome

###########################
# --- General options --- #
###########################

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "MyWebsite.com"

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: false

# Add a search button to the navbar
post_search: false

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: true

# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
# If this setting is off, then long sub-menu words might get cut off
# See https://github.com/daattali/beautiful-jekyll/issues/765 to understand the issue this setting can solve
navbar-var-length: true

# The keywords to associate with your website, for SEO purposes
#keywords: "my,list,of,keywords"

######################################
# --- Colours / background image --- #
######################################

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-col: "#0D3B7F"
navbar-col-dropDown: "#EBEBEBA0"
navbar-text-col: "#FFFFFF"
navbar-text-col-dropDown: "#000000"
navbar-border-col: "#EBEBEB"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#59C8FF"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#59C8FF"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

navbar-img: "/assets/img/title.jpg"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#59C8FF"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
site-css:
 - "/assets/css/user.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"



################
# --- Misc --- #
################

# Ruby Date Format to show dates of posts
date_format: "%Y年 %m月 %d日"

# Facebook App ID
#fb_app_id: ""

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
paginate_path: "news/page:num"

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189

